### ISSUE TITLE
 How i should use it. Would you please open the tutorial to github?

### ISSUE THREAD

**Issue by xiekang0817** [sdelrio/claymore-exporter#1]
How i should use it. Would you please open the tutorial to github?

**Comment by xiekang0817** [comment]
![360 -1133640](https://user-images.githubusercontent.com/22379547/28751070-17d4cce0-7530-11e7-83b5-1fb6273fe45f.jpg)

**Comment by sdelrio** [comment]
On the readme there is a sample:

```
./claymore -t 192.168.1.34 -f 2 -p 8601
```

Where 192.168.1.34 is the IP where Claymore is running (in my case), change it to your IP

 I didn't try it on windows (if you do try with python 2.7). You can also use the docker version:

- <https://hub.docker.com/r/sdelrio/claymore-exporter/>

The idea is to use the exporter with Prometheus and plot graphs with graphana:

![image](https://user-images.githubusercontent.com/12765729/28752488-3b72affa-7521-11e7-9771-db8514b60a19.png)

**Comment by sdelrio** [comment]
Did it work for you? @xiekang0817 
Or I should update the README.md with more detailed info.

**Comment by sdelrio** [comment]
I will close the case now. I've added the `-t`to the README.md.
