### ISSUE TITLE
Support for jsonrpc miner_getstat2

### ISSUE THREAD

**Issue by misach** [sdelrio/claymore-exporter#2]
Hi sdelrio
I added some support for  jsonrpc miner_getstat2. I put it into a separate fork.
Please feel free to just copy the code over. It's not fully finished but it will work for single mining.
Some der stats are not in but before I add them I'd like to have a quick exchange with you regarding design of the metrics.
Feel free to add me as a contributor for your project.
BR misach

**Comment by sdelrio** [comment]
Interesting, I didn’t knew about the getstat2, I can test it with several cards. I don’t use dual mining much at all but I could test. Just I don’t have much time to spare.

**Comment by misach** [comment]
Fix given in separate branch.
